import pyautogui, time
Destination = pyautogui.prompt(text="Enter the texte where you to go", title="Destination",default='')
time.sleep(1)
pyautogui.press('win',interval=0.5)
pyautogui.write('chrome',interval=0.5)
time.sleep(1)
pyautogui.press('enter',interval=0.5)
time.sleep(1)
pyautogui.write(Destination)
time.sleep(1)
pyautogui.press('enter',interval=0.5)
time.sleep(5)
pyautogui.click(x=345, y=417)
time.sleep(1)